### ISSUE TITLE
Integration hangs on install

### ISSUE THREAD

**Issue by jtcm222** [xannor/ha_shinobicctv#3]
When adding the integration the process just tries to load forever and then aborts.

Running HassIO 0.118.4

**Comment by xannor** [comment]
At which point is it getting stuck? Does it prompt for the host and key? Or is it not even getting to that point? Also are any errors in the logs?

**Comment by jtcm222** [comment]
I just tried again, to try to capture some log details and it went through. Looks like it was an error on my part. When I copied and pasted the API key it was adding spaces to the end that I had to delete.

However now the cameras are showing as unavailable in the integrations and dashboard.
If I click on the unavailable entity on the dashboard I get a Login attempt failed notification as well.

**Comment by xannor** [comment]
I am still working out how you are supposed to show errors on the forms, I am following the examples I can find, but it seems like their GUI is a bit more simplistic. I also need to write up some directions. 

Something you can try is remove the intergration,  re-add it, leave the api key and group key blank, and it will do a second prompt for a user/pass, this will only be used to generate an api key and get the group key of the user. This creates an API key with the default permissions, but it would eliminate a mis-type of either key.

**Comment by xannor** [comment]
I have a new release that should handle missing camera info, let me know if this solves your issue.
