### ISSUE TITLE
Lost at how to use after setting up

### ISSUE THREAD

**Issue by ovizii** [xannor/ha_shinobicctv#4]
Hi, could you please add some info on how to use the integration?

I have enabled it, connected to my shinobi instance, an API key got generated but I am lost at what I can do with the integration.

So far I have managed to add my test camera as an instance and it shows idle. Not really great so far :-) 

![image](https://user-images.githubusercontent.com/837902/101980933-5332c180-3c69-11eb-9dad-3fdfb71a73f4.png)

if I click on it, the preview seems broken.

![image](https://user-images.githubusercontent.com/837902/101980945-63e33780-3c69-11eb-9fd1-659174c0c875.png)

![image](https://user-images.githubusercontent.com/837902/101980951-6e9dcc80-3c69-11eb-9049-945f86599be8.png)

Not sure what should be possible with this integration and what not, any pointers are appreciated.

**Comment by xannor** [comment]
This is why I needed testers as it is in a "works for me" state. It creates the entities automatically and they follow a setup similar to the generic camera control. I think this relies on MJPEG by default. Do you have the JPEG API enabled for your cameras in Shinobi? If not could you enable it for one camera and see if it starts to show up in HA? I may have to do more research into how/what the camera system of HA expects.

**Comment by xannor** [comment]
I have a new release that should handle the missing previews and videos. I added ffmjpeg support so it now will convert streams to what HA expects and will also grab stills from the stream if not provided. Let me know if this solves the issue.

**Comment by ovizii** [comment]
thanks for taking up my question. I am quite new to HA and shinobi. 
I just realized there is a new HA core and OS update available, so lets update all of them and your integration first. 

OK, after updating I still see this in HA:
![image](https://user-images.githubusercontent.com/837902/102069871-a0946780-3dfe-11eb-950c-21b05f53fe6f.png)

but now, when clicking on this camera, I see a still image of the cam footage. Pretty nice. Is this how its supposed to work? 
EDIT
I see a still image when using Google Chrome from my Windows PC and actual live footage when using the HA android app.

Would it be possible to see the still image, straight in HA without having to click?


btw. I assume this is what you meant in your first reply? I can't find any documentation, can you share your settings for this section or do you by any chance have a helpful link?

![image](https://user-images.githubusercontent.com/837902/102066147-c408e380-3df9-11eb-9c30-ddfd34a4ce81.png)

**Comment by xannor** [comment]
My recent versions (0.2.0 for 0.118.5 and 0.2.1 for 2020.12.0+) do not require the JPEG API to be set anymore, though it shouldn't hurt either. The default entity created, should have a still image as a preview and show a live feed when viewed (i.e. clicked). 

As for Shinobi, they have decent documentation for their basic features, but everything else, I have had to find via trial and error and scouring the internet.

**Comment by ovizii** [comment]
Thanks. I kept fiddling and all is well. Your integration adds my shinobi cameras as entities and it does that well. Everything else is basically HA's business and I am still experimenting here.

Thanks for your support and the integration.

**Comment by ovizii** [comment]
oh, please let me add a related question, so as not to open an unrelated thread but I think you are the right person to give me a hint:

I found out about this HA integration: https://www.home-assistant.io/integrations/ffmpeg_noise/ basically it watches a mpeg stream and triggers by audio volume. 

Would I point it to the camera stream, to a shinobi stream or somehow to a camera instance of HA?

**Comment by xannor** [comment]
The integration you found would require access to the stream, and that stream passing audio through. I could add an attribute to the entities to provide the primary stream from Shinobi. Then you could use a template in the integration setup to get the stream.
Otherwise you would need direct access to the stream, which with Shinobi, is not difficult, if you understand using REST APIs, or via the camera directly.

Ideally Shinobi should do the detection, but I have not worked out yet how to get notified for detection events.

Edit:
If you are just using this for one camera, you could probably not use Shinobi, and just setup the feeds in HA, using the generic camera integration and the motion and sound ffmpeg integrations. Shinobi is more useful for a centralized point that multiple cameras are monitored from.

**Comment by ovizii** [comment]
Thanks, I managed to connect to the shinobi stream and successfully trigger events upon noise detection.

I know shinobi is only useful for multiple cameras but I might be getting more :-) 

At the moment, I only have 1 reolink camera, for accessing it quickly I use their app at the moment, its benefit over other methods (i.e. shinobi android app) is that it supports some kind of push-to-talk method. I'm basically just checking in on my doggy at home with it :-) 

The limitation is recording to sd card only and not as many options as shinobi has.

If I get more cameras and want to record and trigger by motion, etc. I will use shinobi for it.


Thanks for all your advice, it has been very helpful.
